version: "3"

services:
  app:
    image: tesseract5.de.locale:0.1
    container_name: train-ocr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: sh start.sh
